### ISSUE TITLE
Provide an upgrade path for SDKv2 providers

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#158]
As we build out the framework and it becomes a viable replacement for SDKv2, we need to define the migration path for providers built on SDKv2 to be built on framework, instead. We don't want to make provider devs rewrite their entire provider in one fell swoop. Ideally, people would be able to migrate over one resource at a time. This is going to take some doing, so we can keep practitioner-facing breaking changes in the control of provider developers.

* [x] hashicorp/terraform-plugin-mux#19
  * needed so we can have two protocol 6 providers muxed together
* [x] hashicorp/terraform-plugin-go-contrib#7
  * needed to make SDKv2 providers into protocol 6 providers
* [x] #85 
  * needed so provider blocks that use blocks can match (which mux requires)
  * needed so resources that use blocks can be upgraded without requiring a breaking change
* [x] #214
  * should be verified to ensure migration without the special SDKv2 logic works as expected
* [x] #222
  * needed so blocks have parity with attributes
* [x] ~#159~
  * ~even when providers can control it, it may be too much to ask of practitioners to insert `=` in so many places. If we ever want to get rid of blocks support, we need to solve this problem somehow.~ (out of scope)
* [x] Create terraform.io SDK -> framework migration page, which outlines the optional process of using terraform-plugin-mux functionality to individually migrate resources

**Comment by bflad** [comment]
The last item, creating a terraform-plugin-sdk migration guide, is started here: https://www.terraform.io/plugin/framework/migrating

Closing!
